from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField


# The blog post model
# Required = title, image(optional), description, content,
# slug url, date_posted //autogenerated
# and an author, default = admin
STATUS = [
    (0, 'Draft'),
    (1, 'Published')
]


# categories for various articles
CATEGORIES = [
    (1, 'Trending'),
    (2, 'Latest'),
    (3, 'Education'),
    (4, 'Tech'),
    (5, 'Sports'),
    (6, 'news')
]


class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(blank=True,
                              upload_to='static/images', default=None)
    description = models.CharField(max_length=200)
    content = RichTextField()
    slug = models.SlugField(unique=True)
    date_posted = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(choices=STATUS, default=0)
    post_category = models.IntegerField(choices=CATEGORIES, default=1)
    author = models.ForeignKey('self', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'slug': self.slug})
